In [9]:
import numpy as np

### Bài 4: Combine rooms

An được giao nhiệm vụ tổ chức thi tiếng Anh trên máy tính cho hai phòng với 7 bạn mỗi bên. Tuy nhiên, vì hôm ấy chỉ còn 1 phòng máy trống, An phải lựa chọn thí sinh để đảm bảo có nhiều nhất 7 bạn tham gia.

An cũng biết được phòng 2 có thể thay bằng hình thức thi giấy. An đặt hai danh sách hai bên, chọn lựa giữa hai bạn vị trí đầu tiên, thứ hai, thứ ba,... đến hết. Tiêu chí chọn như sau: 
- Giữa phòng 1 và 2, ưu tiên phòng 1. 
- Nếu thí sinh phòng 1 xin thôi thi, chọn thí sinh còn lại. 
- Nếu cả hai thí sinh đều thôi thi, gán “None” để bổ sung sau. 

Viết hàm nhận vào hai mảng numpy một chiều chứa số thứ tự thí sinh. Trả về mảng chứa danh sách thí sinh cuối cùng. Lưu ý rằng số thứ tự giữa hai phòng không trùng nhau và thí 
sinh thôi thi có số thứ tự âm. Ví dụ: 
- 𝑟𝑜𝑜𝑚_1 = [1, 2, -3, 4, 5,6, -7]
- 𝑟𝑜𝑜𝑚_2 = [8,9,10,11,12, -13, -14]

Đáp án là: [1,2,10,4,5,6, 𝑁𝑜𝑛𝑒]. 

Tên hàm: **combine_rooms(room_1, room_2)**

In [14]:
def commine_rooms(room1, room2):
    result = []
    for i in range(len(room1)):
        if room1[i] >= 0:
            result.append(room1[i])
        elif room2[i] >= 0:
            result.append(room2[i])
        else:
            result.append(None)

    return np.array(result)


if __name__ == "__main__":
    room1 = np.array([1, 2, -3, 4, 5,6, -7])
    room2 = np.array([8,9,10,11,12, -13, -14])
    print(commine_rooms(room1, room2))

[1 2 10 4 5 6 None]


### Bài 5
![image](./images/W02_05.jpg)

In [4]:
def broadcast(vec, n):
    return np.tile(vec, (1, n))

if __name__ == "__main__":
    vec = np.array([[1], [2], [3]])
    print(broadcast(vec, 4))

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


### Bài 6: Ma trận chuyển vị (transpose) được tạo ra bằng cách lật ma trận ban đầu theo trục chéo:

![image](https://upload.wikimedia.org/wikipedia/commons/e/e4/Matrix_transpose.gif)

In [6]:
def transpose(matrix):
    return np.transpose(matrix)

if __name__ == "__main__":
    matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print("Ma trận ban đầu: ")
    print(matrix)

    print("Ma trận chuyển vị: ")
    print(transpose(matrix))

Ma trận ban đầu: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ma trận chuyển vị: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Bài 7: Tích ma trận và tích hadamard là hai phép tính phổ biến. Hãy viết chương trình nhận hai ma trận đầu vào, in trên màn hình tích của chúng. Nếu không thể tính, hãy in “Khong co tich ma tran” hoặc “Khong co tich Hadamard”. 

In [13]:
def product(matrix1, matrix2):
    if matrix1.shape[1] != matrix2.shape[0]:
        return "Khong co tich ma tran"
    
    return np.dot(matrix1, matrix2)

def Hadamard(matrix1, matrix2):
    if matrix1.shape != matrix2.shape:
        return "Khong co tich Hadamard"
    
    return np.multiply(matrix1, matrix2)

if __name__ == "__main__":
    matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
    matrix2 = np.array([[1, 2], [3, 4], [5, 6]])

    print("Tích của hai ma trận: ")
    print(product(matrix1, matrix2))

    print("Hadamard của hai ma trận: ")
    print(Hadamard(matrix1, matrix2))

Tích của hai ma trận: 
[[22 28]
 [49 64]]
Hadamard của hai ma trận: 
Khong co tich Hadamard


### Bài 8: Viết hàm nhận tham chiếu là ma trận và số chỉ mục của cột. Thay toàn bộ giá trị cột đó là 1 rồi trả về kết quả. 

In [17]:
def replace_col(mat, col_ind):
    '''Relace column col_ind of matrix mat with a column of ones (1)
    Args:
        mat: a numpy matrix
        col_ind: index of column to be replaced (0-based)

    Returns:
        a numpy matrix with column col_ind replaced with a column of ones (1)

    Example:
        mat = np.array([[1, 2, 3], [4, 5, 6]]) \n
        replace_col(mat, 1) = np.array([[1, 1, 3], [4, 1, 6]])
    '''

    mat[:, col_ind] = 1
    return mat

if __name__ == "__main__":
    mat = np.array([[1, 2, 3], [4, 5, 6]])
    print("Ma trận ban đầu: ")
    print(mat)

    col_ind = int(input("Nhập chỉ số cột cần thay thế: "))
    print("Ma trận sau khi thay thế cột " + str(col_ind) + " bằng một cột toàn số 1: ")
    print(replace_col(mat, col_ind=col_ind))

Ma trận ban đầu: 
[[1 2 3]
 [4 5 6]]
Ma trận sau khi thay thế cột 1 bằng một cột toàn số 1: 
[[1 1 3]
 [4 1 6]]
