In [4]:
import numpy as np

### Bài 6: Ma trận chuyển vị (transpose) được tạo ra bằng cách lật ma trận ban đầu theo trục chéo:

![image](https://upload.wikimedia.org/wikipedia/commons/e/e4/Matrix_transpose.gif)

In [6]:
def transpose(matrix):
    return np.transpose(matrix)

if __name__ == "__main__":
    matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print("Ma trận ban đầu: ")
    print(matrix)

    print("Ma trận chuyển vị: ")
    print(transpose(matrix))

Ma trận ban đầu: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ma trận chuyển vị: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Bài 7: Tích ma trận và tích hadamard là hai phép tính phổ biến. Hãy viết chương trình nhận hai ma trận đầu vào, in trên màn hình tích của chúng. Nếu không thể tính, hãy in “Khong co tich ma tran” hoặc “Khong co tich Hadamard”. 

In [13]:
def product(matrix1, matrix2):
    if matrix1.shape[1] != matrix2.shape[0]:
        return "Khong co tich ma tran"
    
    return np.dot(matrix1, matrix2)

def Hadamard(matrix1, matrix2):
    if matrix1.shape != matrix2.shape:
        return "Khong co tich Hadamard"
    
    return np.multiply(matrix1, matrix2)

if __name__ == "__main__":
    matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
    matrix2 = np.array([[1, 2], [3, 4], [5, 6]])

    print("Tích của hai ma trận: ")
    print(product(matrix1, matrix2))

    print("Hadamard của hai ma trận: ")
    print(Hadamard(matrix1, matrix2))

Tích của hai ma trận: 
[[22 28]
 [49 64]]
Hadamard của hai ma trận: 
Khong co tich Hadamard
