Bài 6: Ma trận chuyển vị (transpose) được tạo ra bằng cách lật ma trận ban đầu theo trục chéo:

![image](https://upload.wikimedia.org/wikipedia/commons/e/e4/Matrix_transpose.gif)

In [3]:
import numpy as np

def transpose(matrix):
    return np.transpose(matrix)

if __name__ == "__main__":
    matrix = np.array([[1, 2, 3], [4, 5, 6]])
    print("Ma trận ban đầu: ")
    print(matrix)

    print("Ma trận chuyển vị: ")
    print(transpose(matrix))

Ma trận ban đầu: 
[[1 2 3]
 [4 5 6]]
Ma trận chuyển vị: 
[[1 4]
 [2 5]
 [3 6]]
